#ifndef TESTLIBRART_GLOBAL_H
#define TESTLIBRART_GLOBAL_H


#if defined(TESTLIBRART_LIBRARY)
#  define TESTLIBRARTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTLIBRARTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTLIBRART_GLOBAL_H
